databases:
  - name: flash_account
    databaseName: flash_account
    user: flash_account

services:
  - type: web
    name: flash_account
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn -b 0.0.0.0 backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flash_account
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4